spring :
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 794728723624-4fbqthdk5gecoog9mnkh9vg2rjctck2h.apps.googleusercontent.com
            client-secret: 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
            redirect_uri: http://localhost:8080/login/oauth2/code/google
            scope: email, profile
          naver:
            client-id: l67JOTGhm4e5vEOdypKo
            client-secret: 0KgO0TMfcV
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: name, email
          kakao:
            client-id: 66a79b288e606392a0cdad0c622fa76a
            client-secret: y9mMUkIlySWuFKM1DMQmYhvviCS71lzs
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: account_email, profile_nickname

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
